this is a test
jaybee84/ml-in-rd pull request #119
Opened 2020-10-12 19:38 UTC by allaway

### Purpose

### Directions for reviewers

#### Which areas should receive a particularly close look?

#### Is there anything that you want to discuss further?

#### Is the pull request ready for review?

### Manuscript checklist

Unless otherwise noted above, this PR will be considered ready for review when all four items have been checked.

- [ ] All changes to text follow "one sentence per line" [[Manubot instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#manubot-markdown)]
- [ ] All citations follow the [Manubot citation instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#citations)
- [ ] All changes or additions to tables follow the [Manubot table instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#tables)
- [ ] All figures follow the [Manubot figure instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#figures)
- [ ] All terms that need to be added to glossary have been added to #50 
- [ ] There are no new spelling errors identified by the Manubot spellchecker

2020-10-13 03:17 UTC, allaway commented
This is not _actually_ ready for review, but please feel free to leave comments or suggestions at any time.

2020-10-13 03:18 UTC, allaway commented
Alternate section title: https://www.youtube.com/watch?v=gj3dPe2vJHo

2020-10-14 23:13 UTC, jaybee84 requested changes
I realize this is still in prep, but I added a few comments and preliminary edits. :)

2020-10-14 23:13 UTC, jaybee84 commented on content/03.heterogeneity.md
> +### Dealing with complex high-dimensional rare disease data
```suggestion
### Manage complex high-dimensional rare disease data
```

2020-10-14 23:13 UTC, jaybee84 commented on content/03.heterogeneity.md
> +Even if we momentarily ignore the desire to statistically interrogate our data, simply untangling the many correlated features and interpreting how they relate to the biological question at hand can
```suggestion
Additionally, simply untangling the many correlated features and interpreting how they relate to the biological question at hand can make the use of highly dimensional rare disease data for discovery daunting. 
```

2020-10-14 23:13 UTC, jaybee84 commented on content/03.heterogeneity.md
> +This is known as the "curse of dimensionality," and can be a major impediment to the use of data-rich methods in sample-deficient contexts [@doi:10.1038/nrc2294].
```suggestion
This is known as the "curse of dimensionality," and can be a major impediment to the use of data-rich statistical methods in sample-deficient contexts [@doi:10.1038/nrc2294].
```

2020-10-14 23:13 UTC, jaybee84 commented on content/03.heterogeneity.md
> +Furthermore, rare disease data collection and aggregation methods can further complicate these challenges by introducing more variability into the data at hand.
```suggestion
Furthermore, rare disease data collection and aggregation methods can further complicate these challenges by introducing technical variability into the data at hand. 
```

2020-10-14 23:13 UTC, jaybee84 commented on content/03.heterogeneity.md
> +<!--RJA TODO: Add examples? Not sure how useful-->
I like the idea of adding a few examples. I think it helps crystallize the concepts talked about in the section and gives an audience of new practitioners a good place to start their deep dive.

2020-10-14 23:13 UTC, jaybee84 commented on content/03.heterogeneity.md
> +Representation learning is the process of learning features from raw data, where a feature is an individual variable.
I am assuming what is implied here is that a feature once learned becomes a singular variable, since features themselves can be an aggregate of few different variables. It would be helpful to clarify that here I think.

2020-10-14 23:13 UTC, jaybee84 commented on content/03.heterogeneity.md
> +<!-- RJA NOTE: this next sentence seems to be in conflict with the crux of the intro I wrote to this section - not sure how best to fix this -->
Discussing representation learning in the context of "Feature-representation-transfer" as done in the "Transfer, multitask, and few-shot learning" section may be helpful in resolving this conflict.

2020-10-14 23:17 UTC, jaybee84 commented
Re: <!-- TODO: Refs! --> on L43 of the new version - what is this referring to? where is the missing ref?

I think this was referring to the section where you had discussed tapping into domain knowledge of experts (in the context of surgical procedures introducing technical/biological artifacts in the data) as one of the things people should consider while working with rare disease data.

2020-10-14 23:30 UTC, allaway commented on content/03.heterogeneity.md
> +This is known as the "curse of dimensionality," and can be a major impediment to the use of data-rich methods in sample-deficient contexts [@doi:10.1038/nrc2294].
Ah, here I was referring to data generation methods, not statistical methods. Will clarify this

2020-10-14 23:33 UTC, allaway commented
> Re:
> <-- TODO: Refs! on L43 of the new version - what is this referring to? where is the missing ref?>
> 
> I think this was referring to the section where you had discussed tapping into domain knowledge of experts (in the context of surgical procedures introducing technical/biological artifacts in the data) as one of the things people should consider while working with rare disease data.

That's what I thought at first too, but that had it's own "add ref" note, so I thought this one might be referring to something else.

2020-10-14 23:44 UTC, allaway commented on content/03.heterogeneity.md
> +<!-- RJA NOTE: this next sentence seems to be in conflict with the crux of the intro I wrote to this section - not sure how best to fix this -->
The conflict that I see is basically that this method says it requires a lot of data, whereas the thesis to the section states that dimensionality reduction is one way of resolving issues with overcoming the curse of dimensionality. Not clear to me what you're suggesting and if it solves this conflict - can you provide more details (or, if you have the inclination, take a stab at it)?

2020-10-14 23:45 UTC, allaway commented
> I realize this is still in prep, but I added a few comments and preliminary edits. :)

That's great - thank you!

2020-10-22 18:07 UTC, jaybee84 commented on content/03.heterogeneity.md
>  Representation learning tends to be data-intensive; many samples are required.
```suggestion
Representation learning tends to be data-intensive (i.e. many samples are required) and thus may seem to aggravate the curse of dimensionality.
But representation learning when applied to learn low dimensional patterns from large datasets and then applying those patterns to smaller but related datasets can be a powerful tool for dimensionality reduction.
In the later sections of this perspective, we will discuss this method of leveraging large datasets to reduce dimensionality in smaller datasets, also known as _feature-representation-transfer_ .
```

2020-10-22 18:09 UTC, jaybee84 commented on content/03.heterogeneity.md
> +<!-- RJA NOTE: this next sentence seems to be in conflict with the crux of the intro I wrote to this section - not sure how best to fix this -->
I added a couple of sentences to elaborate on my comment above. Let me know if it makes sense or if you were envisioning a different angle to this part :)

2020-10-26 00:19 UTC, jaclyn-taroni commented on content/03.heterogeneity.md
>  Representation learning tends to be data-intensive; many samples are required.
Agree with @jaybee84 's adds here!

2020-10-26 18:14 UTC, allaway commented on content/03.heterogeneity.md
> +<!-- RJA NOTE: this next sentence seems to be in conflict with the crux of the intro I wrote to this section - not sure how best to fix this -->
Thanks, this change looks great!

2020-10-26 18:25 UTC, allaway commented on content/03.heterogeneity.md
> +<!--RJA TODO: Add examples? Not sure how useful-->
```suggestion
```

2020-10-26 18:39 UTC, cgreene commented on content/03.heterogeneity.md
>  Rare disease data often suffers from artifacts introduced by non-biological phenomena such as batch or assay platform.[@doi:10.1016/j.cels.2019.04.003, @doi:10.1186/s13023-020-01376-x, @doi:10.1038/s
```suggestion
Rare disease data often suffers from artifacts introduced by non-biological phenomena such as batch or assay platform [@doi:10.1016/j.cels.2019.04.003, @doi:10.1186/s13023-020-01376-x, @doi:10.1038/s41591-019-0457-8].
```

2020-10-26 18:39 UTC, cgreene commented on content/03.heterogeneity.md
>  <!-- TODO: Refs! -->
```suggestion
```

2020-10-26 18:41 UTC, jaybee84 approved these changes

2020-10-26 19:50 UTC, allaway commented on content/03.heterogeneity.md
>  <!-- TODO: If we talk about *feature selection* in addition to feature/representation learning, that might set up model complexity nicely! -->
```suggestion
```

Addressed further down in revisions.

2020-10-26 19:56 UTC, allaway commented on content/03.heterogeneity.md
> +The output of these  can then be used to visualize structure in the data, used to define subgroups within data (either biological, or technical, as discussed in the next section), or can be used as p
```suggestion
The output of these can then be used to visualize structure in the data (e.g. [@doi:10.1038/s41467-019-13056-x]), used to define subgroups within data (e.g. [@doi:10.1038/s41467-020-15351-4], or can be used for feature selection/extraction during machine learning (e.g. [@doi:10.1007/978-3-030-03243-2_299-1]). 
```

2020-10-26 20:04 UTC, merged

2020-10-26 20:51 UTC, jaybee84 commented on content/03.heterogeneity.md
> +Representation learning is the process of learning features from raw data, where a feature is an individual variable.
@allaway I am not sure this is fully resolved yet.