Breakout discussion of combining datasets into own section
jaybee84/ml-in-rd pull request #188
Opened 2021-08-31 14:43 UTC by jaclyn-taroni

### Purpose

Here I'm adding a first pass at breaking out the discussion of combining multiple datasets – previously contained in the section that covered dimensionality reduction – into its own section that will come right after the intro (#187). This is designed to complement the new box that will cover the basics of experimental design (#186). 

### Directions for reviewers

I would recommend looking at (or revisiting) #183 for context. That is intended to set the stage for our new audience and it's important that the content of this pull request is correctly pitched for the intended audience.

#### Which areas should receive a particularly close look?

I'm not happy about the wording in the last paragraph right now, so suggestions there are welcome in particular!

#### Is the pull request ready for review?

Yes. I don't expect that what gets merged will necessarily look like what I submit initially, but feedback at this stage seems warranted.

### Manuscript checklist

Unless otherwise noted above, this PR will be considered ready for review when all four items have been checked.

- [x] All changes to text follow "one sentence per line" [[Manubot instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#manubot-markdown)]
- [x] All citations follow the [Manubot citation instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#citations)
- [ ] There are no new spelling errors identified by the Manubot spellchecker

2021-09-03 20:10 UTC, jaybee84 commented
Contingent on #185

2021-09-03 20:19 UTC, jaclyn-taroni commented
Based on conversation today: consider moving up some of the information in _Emphasis on not just "more n" but "more meaningful n"_ section in Outlook.

2021-09-03 23:02 UTC, jaybee84 requested changes
added some more to the ML ready dataset part :)

2021-09-03 23:02 UTC, jaybee84 commented on content/03.combining-datasets.md
> +More features often means increased missing observations (_sparsity_), more dissimilarity between samples, and increased redundancy between individual features or combinations of features [@doi:10.10
```suggestion
More features often means increased missing observations (_sparsity_), more dissimilarity between samples (_variance_), and increased redundancy between individual features or combinations of features (_collinearity_) [@doi:10.1038/s41592-018-0019-x], all of which contribute to a challenging prediction problem.
```

2021-09-03 23:02 UTC, jaybee84 commented on content/03.combining-datasets.md
> +If a small sample size compromises an ML model's performance, then an intuitive solution is to increase the number of samples.
```suggestion
If a small sample size compromises an ML model's performance, then two approaches can be taken to improve the outcome: 1) increase the number of samples to reduce sparsity, variance, and collinearity, 2) improve the quality of samples to account for sparsity, variance, and collinearity
```

2021-09-03 23:02 UTC, jaybee84 commented on content/03.combining-datasets.md
> +An individual rare disease cohort may be necessarily small, but appropriate training, testing and validation sets could be constructed by combining multiple cohorts [TODO: Link to experimental design
```suggestion
In the first approach, appropriate training, testing, and validation sets could be constructed by combining multiple small individual rare disease cohorts [TODO: Link to experimental design box #185].
```

2021-09-03 23:02 UTC, jaybee84 commented on content/03.combining-datasets.md
> +Not only can data collection differ from cohort to cohort, but the aggregation methods selected can introduce technical variability which can negatively impact researchers ability to learn or detect
```suggestion
In doing so, special attention should be directed towards harmonization since data collection can differ from cohort to cohort.
Without careful selection of aggregation methods, one may introduce technical variability into the aggregated dataset which can negatively impact the ML model's ability to learn or detect meaningful signal.
```

2021-09-03 23:02 UTC, jaybee84 commented on content/03.combining-datasets.md
> +
In the second approach,  small but meaningfully generated datasets can greatly enhance the performance of ML models in the context of rare disease.
Specifically, improving labeling of data is critical in accounting for sparsity and variance in the data. 
In our experience, collaboration with domain experts has proved to be critical in gaining insight into potential sources of variation in the datasets.
An anecdotal example from the authors' personal experience: conversations with a rare disease clinician revealed that samples in a particular tumor dataset were collected using vastly different surgical techniques (laser ablation and excision vs standard excision). 
This information that was not readily available to non-experts, but was obvious to the clinician. 
Addition of this kind of important metadata or labels to the samples can greatly help ML models become more effective in extracting biologically relevant patterns.
Such instances underline the fact that continuous collaboration with domain experts and the sharing of well-annotated data is needed to generate robust datasets in the future.

2021-09-03 23:04 UTC, jaybee84 commented on content/03.combining-datasets.md
> +
brought in some of the text in the outlook section

2021-09-10 18:21 UTC, jaybee84 approved these changes

2021-09-10 18:22 UTC, jaybee84 commented
@jaclyn-taroni are you okay with resolving the above additions/comments?

2021-09-10 18:46 UTC, jaclyn-taroni commented on content/03.combining-datasets.md
> +In the next section, we will discuss approaches that can aid in identifying and visualizing structure in datasets.
```suggestion

In the next section, we will discuss approaches that can aid in identifying and visualizing structure in datasets.
```

2021-09-10 18:46 UTC, jaclyn-taroni commented
Yup - I turned one of the comments from you into a `suggestion` proper and then included all suggestions in https://github.com/jaybee84/ml-in-rd/pull/188/commits/8ece24560eb565b62bc258c495889eccf9b6311c

2021-09-10 19:22 UTC, jaybee84 requested changes

2021-09-10 19:22 UTC, jaybee84 commented on content/03.combining-datasets.md
> +
```suggestion
Ideally, structure in the composite datasets under study will be aligned with variables of interest, such as phenotype labels if available; if instead samples from the same cohort tend to group together regardless of phenotype, revisiting the construction of the dataset is warranted.
```

2021-09-10 19:22 UTC, jaybee84 commented on content/03.combining-datasets.md
> +Ideally, structure in the composite datasets under study will be aligned with variables of interest, such as phenotype labels if available; if instead samples from the same cohort tend to group toget
```suggestion

```

2021-09-24 21:05 UTC, jaybee84 approved these changes

2021-09-24 21:05 UTC, jaybee84 commented on content/03.combining-datasets.md
> +This information that was not readily available to non-experts, but was obvious to the clinician.
```suggestion
This information was not readily available to non-experts, but was obvious to the clinician. 
```

2021-09-24 22:04 UTC, merged