Jaclyn taroni/2023 02 19 edits
jaybee84/ml-in-rd pull request #242
Opened 2023-02-19 23:37 UTC by jaclyn-taroni

Stacked on #238 

Summarizing changes:

* Changed Box 3 to follow one sentence per line convention. There are a couple minor changes in there as well.
* Removed reference to complex phenotypes and complex data from the synopsis. I also changed our reference to "large amounts of complex data" because it was somewhat imprecise.
* Fixed the Figure 1 legend per reviewer's comments.
* Revised a bunch of language in Box 1 per reviewer's comments (e.g., "held-out test set" becomes "held-out validation set").
* Added a TODO about updating the LASSO reference.

I'd like to take another look at Box 3 tomorrow, so I'm marking as a draft for now.

2023-02-20 00:15 UTC, jaybee84 commented
@jaclyn-taroni  Thanks for starting this draft.

I was just taking a look at the changes, and it looks like a bunch of changes that I had already made in the original (word doc) did not port correctly to the PR .. e.g. 
> Removed reference to complex phenotypes and complex data from the synopsis. I also changed our reference to "large amounts of complex data" because it was somewhat imprecise.
> Fixed the Figure 1 legend per reviewer's comments.
> Revised a bunch of language in Box 1 per reviewer's comments (e.g., "held-out test set" becomes "held-out validation set").

Thanks for going through those and fixing/updating those. Looking forward to your finalized changes.

2023-02-21 13:41 UTC, jaclyn-taroni commented
I'm going to mark this ready for review for the benefit of running the other checks.

2023-02-21 18:52 UTC, jaclyn-taroni commented
Okay, with https://github.com/jaybee84/ml-in-rd/pull/242/commits/c03e15298b10f727e93a9b65044f3cbc827a474e, I made a few tweaks to where the new box (Box 1) is referenced. Some references seemed too low context given what the sentenced around them actually said – a reader is unlikely to be familiar with the papers cited – so I've either removed something or made it clear it was an example by adding `e.g.,`.

2023-02-21 18:57 UTC, jaybee84 commented on content/05.model-complexity.md
> +Thus, regularization methods like LASSO or elastic-net are beneficial in ML with rare observations, and are worth exploring in the context of rare diseases.[@doi:10.1371/journal.pgen.1004754] <!--TOD
```suggestion
Thus, regularization methods like LASSO or elastic-net are beneficial in ML with rare observations, and are worth exploring in the context of rare diseases.[@doi:10.1186/s10020-023-00603-y] <!--TODO: replace this reference-->
```

2023-02-21 20:38 UTC, jaybee84 requested changes
added some minor comments. otherwise look good to me..

2023-02-21 20:38 UTC, jaybee84 commented on content/01.synopsis.md
> +These approaches provide a rich portrait of genes, molecular pathways, and cell types involved in rare disease phenotypes.
```suggestion
These approaches provide a rich portrait of genes, molecular pathways, and cell types involved in disease phenotypes. 
```

2023-02-21 20:38 UTC, jaybee84 commented on content/01.synopsis.md
>  Precision medicine also presents a similar challenge, where patients with common diseases are partitioned into small subsets of patients based on particular characteristics.
```suggestion
```

2023-02-21 20:38 UTC, jaybee84 commented on content/06.prior-knowledge.md
> +There are a variety of tactics to sift through the data encoded in knowledge graphs.
```suggestion
There are a variety of tactics to sift through the large amounts of data encoded in knowledge graphs.
```

2023-02-21 20:38 UTC, jaybee84 commented on content/05.model-complexity.md
> +Additional approaches like combining random forests with resampling without replacement can generate confidence intervals for the model predictions by iteratively exposing the models to incomplete da
```suggestion
Additional approaches like combining random forests with resampling without replacement can generate confidence intervals for the model predictions (e.g. for applications like Box 1d) by iteratively exposing the models to incomplete datasets, mimicking real world cases where most rare disease datasets are incomplete [@doi:10.3390/genes11020226].
```

2023-02-21 20:42 UTC, jaybee84 commented
@jaclyn-taroni I see that you did not make any changes to the `outlook.md` file where we refered to the excluded methods. Is it okay to assume that you did not have any additional edits there?

2023-02-21 21:34 UTC, jaclyn-taroni commented on content/05.model-complexity.md
> +Additional approaches like combining random forests with resampling without replacement can generate confidence intervals for the model predictions by iteratively exposing the models to incomplete da
```suggestion
Additional approaches like combining random forests with resampling without replacement can generate confidence intervals for the model predictions (e.g., for applications like Box 1d) by iteratively exposing the models to incomplete datasets, mimicking real world cases where most rare disease datasets are incomplete [@doi:10.3390/genes11020226].
```

2023-02-21 21:36 UTC, jaclyn-taroni commented
> @jaclyn-taroni I see that you did not make any changes to the `outlook.md` file where we refered to the excluded methods. Is it okay to assume that you did not have any additional edits there?

Yes, no additional edits.

2023-02-21 22:18 UTC, merged