Knowledge graphs
jaybee84/ml-in-rd pull request #71
Opened 2020-07-06 18:26 UTC by allaway

### Purpose

This addresses issue #8. 

### Directions for reviewers

#### Which areas should receive a particularly close look?

#### Is there anything that you want to discuss further?

#### Is the pull request ready for review?

### Manuscript checklist

Unless otherwise noted above, this PR will be considered ready for review when all four items have been checked.

- [ ] All changes to text follow "one sentence per line" [[Manubot instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#manubot-markdown)]
- [ ] All citations follow the [Manubot citation instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#citations)
- [ ] All changes or additions to tables follow the [Manubot table instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#tables)
- [ ] All figures follow the [Manubot figure instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#figures)

2020-07-21 20:50 UTC, allaway commented
It looks like the appveyor build is broken, maybe because of this 404?

`Err:25 https://dl.bintray.com/rabbitmq-erlang/debian bionic Release
  404  Not Found [IP: 52.36.128.157 443`

2020-07-21 21:16 UTC, jaybee84 commented on content/03.prior-knowledge.knowledge-graphs.md
> +More work needs to be done to assess 1) which graph networks and network features best capture the salient information about rare diseases, 2) the utility of an array of knowledge graph analysis meth
```suggestion
More work needs to be done to assess 1) which graph networks and network features best capture the salient information about rare diseases, 2) the utility of an array of knowledge graph analysis methodologies (such as graph neural nets, reinforcement learning approaches, and adversarial learning approaches)[doi:10.1109/TKDE.2020.2981333] to obtain actionable insights about rare diseases and 3) which problems - like drug discovery, identification of novel rare diseases, or assessment of genotype-phenotype relationships - can be meaningfully interrogated using machine learning of knowledge graphs
```

2020-07-21 21:25 UTC, jaybee84 commented
Yeah... I have had that happen to me before when it could not find miniconda. In this case, it is the debian bionic release. It generally resolves if I rerun the checks... so I committed a small edit (removed the period at the end of the PR), and rebuilt the PR. This time the checks went through :)

2020-07-21 21:46 UTC, allaway commented
Hah, appveyor seem to not like me...I changed some spelling and it's once again broken.

2020-07-21 22:49 UTC, jaybee84 commented
It seems your most current push triggered a successful Appveyor build :) 

I have found it useful to have spelling additions separate from the PR that they are originating from. For some reason, the two together break appveyor

2020-07-22 00:16 UTC, allaway commented
> It seems your most current push triggered a successful Appveyor build :)
> 
> I have found it useful to have spelling additions separate from the PR that they are originating from. For some reason, the two together break appveyor

Interesting - I wasn't actually changing the dictionary on this PR, just changing the spelling mistakes in the actual manuscript file. :shrug:

2020-07-22 17:02 UTC, jaybee84 requested changes
This looks great! Added a few comments..

re: [paper](https://academic.oup.com/database/article/doi/10.1093/database/baaa015/5818923) - I think it makes sense to add it. The visualization [portal](http://ngly1graph.org:7474/browser/) is not the most straightforward though.. :(

2020-07-22 17:02 UTC, jaybee84 commented on content/03.prior-knowledge.knowledge-graphs.md
> +Knowledge graphs integrate related-but-different data types, creating a rich and complex data source.
Is it possible to add a bit of detail on how the data types were integrated?

2020-07-22 17:02 UTC, jaybee84 commented on content/03.prior-knowledge.knowledge-graphs.md
> +In the academic rare disease space, there a few pioneering examples of machine learning-based mining of knowledge graphs to identify repurposable drugs [@doi:10.1101/727925] and disease classificatio
This is super interesting. It would be great to go into a bit more detail into these two works to give the readers an intuition of how these may be used in rare disease and what are the significant pitfalls

2020-07-24 00:14 UTC, allaway commented on content/03.prior-knowledge.knowledge-graphs.md
> +Knowledge graphs integrate related-but-different data types, creating a rich and complex data source.
I added line 8, which i think gets at this a bit. My sense is that the actual implementation (ie talking about how to create a graph database)  is beyond the scope of this perspective.

2020-07-24 00:24 UTC, jaybee84 commented on content/03.prior-knowledge.knowledge-graphs.md
> +These graphs connect information like genetic, functional, chemical, clinical, and ontological data to enable the end user to explore many types of data and their relationships with disease phenotype
requesting citation for the computational method bit, otherwise this looks good.

2020-07-28 01:17 UTC, allaway commented on content/03.prior-knowledge.knowledge-graphs.md
> +In the academic rare disease space, there a few pioneering examples of machine learning-based mining of knowledge graphs to identify repurposable drugs [@doi:10.1101/727925] and disease classificatio
OK, let me know if the updated version resolves this comment!

2020-07-29 00:27 UTC, jaybee84 approved these changes
LGTM

2020-07-29 00:27 UTC, jaybee84 commented on content/03.prior-knowledge.knowledge-graphs.md
> +These studies make it clear that there are some challenges in using machine learning in graph databases in rare disease.
```suggestion
These studies make it clear that there are some challenges in using machine learning using graph databases in rare disease.
```

2020-07-29 00:27 UTC, jaybee84 commented on content/03.prior-knowledge.knowledge-graphs.md
> +Consequently, is not yet clear how effective these approaches, and knowledge graphs in general, are in studying a specific disease of interest; more work needs to be done to identify methods that can
```suggestion
Consequently, it is not yet clear how effective these approaches, and knowledge graphs in general, are in studying a specific disease of interest; more work needs to be done to identify methods that can provide actionable insights for a specific rare disease application. 
```

2020-07-29 03:09 UTC, merged